In [3]:
import numpy as np
arr = np.random.randint(5, 21, size=(3, 3))
print("Array:\n", arr)

# Mean of each row
row_means = arr.mean(axis=1)
print("Mean of each row:", row_means)


Array:
 [[ 5 10 15]
 [14 19 13]
 [10 14 20]]
Mean of each row: [10.         15.33333333 14.66666667]


In [5]:
import pandas as pd

data = {
    "Name": ["Aman", "Riya", "Karan", "Sneha", "Rahul"],
    "Score": [72, 55, 81, 60, 45]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

filtered_df = df[df["Score"] >= 60]
print("\nFiltered DataFrame (Score >= 60):\n", filtered_df)


Original DataFrame:
     Name  Score
0   Aman     72
1   Riya     55
2  Karan     81
3  Sneha     60
4  Rahul     45

Filtered DataFrame (Score >= 60):
     Name  Score
0   Aman     72
2  Karan     81
3  Sneha     60


In [7]:
def normalize(data):
    min_val = min(data)
    max_val = max(data)
    return [(x - min_val) / (max_val - min_val) for x in data]

# Example usage
numbers = [10, 20, 30, 40, 50]
normalized_numbers = normalize(numbers)
print("Normalized values:", normalized_numbers)


Normalized values: [0.0, 0.25, 0.5, 0.75, 1.0]


In [9]:

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication
result = np.dot(A, B)
print("Matrix Multiplication Result:\n", result)


Matrix Multiplication Result:
 [[19 22]
 [43 50]]


In [11]:
heart = pd.read_csv("heart.csv")


In [13]:
print("Shape of dataset:", heart.shape)


Shape of dataset: (303, 14)


In [15]:
print("Missing values in each column:\n")
print(heart.isnull().sum())


Missing values in each column:

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64


In [17]:
print("Data types of columns:\n")
print(heart.dtypes)


Data types of columns:

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object


In [21]:
mean_age = heart["age"].mean()
print("Mean Age of patients:", mean_age)


Mean Age of patients: 54.366336633663366


In [27]:
from sklearn.model_selection import train_test_split

selected_data = heart[["age", "sex", "cp", "trestbps", "chol"]]

train_data, test_data = train_test_split(
    selected_data, test_size=0.25, random_state=42
)

print("Training data shape:", train_data.shape)
print("Testing data shape:", test_data.shape)


Training data shape: (227, 5)
Testing data shape: (76, 5)
